server:
  port: 8080

spring:
  application:
    name: apigatewaydemo

  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/students/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/transactions/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
